# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-24 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floorno',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomno',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
